
all: phymlexe phytimeexe raxmlHPC-PTHREADS-SSE3exe mrbayesexe

phymlexe:
	(cd phyml; ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes ./configure; make)

phytimeexe:
	(cd phytime; ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes ./configure --enable-phytime; make)

raxmlHPC-PTHREADS-SSE3exe:
	(cd raxml; make -f Makefile.SSE3.PTHREADS.gcc)

mrbayesexe:
	(cd mrbayes; autoconf; ./configure --with-beagle=no --enable-sse=yes; make)

clean:
	(cd phyml; clean)
	(cd phytime; clean)
	(cd raxml; rm *.o raxml*)
	(cd mrbayes; clean)
